spring.application.name=ViajeSeguroSpringBoot
#configuracion para mysql
spring.datasource.url=jdbc:mysql://localhost:3306/bd_viajeseguro
spring.datasource.username=root
spring.datasource.password=Em150401.


#determinar el driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#uso de jpa hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false